#
# default Configuration
#
#   DO *NOT* CHANGE THIS FILE
#
#   If you want to adjust these settings put them in config.yaml in the core
#   directory of KISS
#


page:

    title:              'Follow the KISS'
    description:        'Empty description'
    author:             'Jakob Holderbaum, Nils Schweinsberg'
    copyright:          'Jakob Holderbaum, Nils Schweinsberg'
 

options:

    app_title:          true    # append page title to main title?
    separator:          ' > '   # maintitle [separator] subtitle
