#
# user settings
#
#   Change this file if you want to adjust/add your settings.
#
#   See cms/Config/defaults.yaml for a list of all possible settings (but
#   *don't* change that file!).
#


page:

    title:              'Follow the KISS'
    description:        'Empty description'
    author:             'Jakob Holderbaum'
    copyright:          'Jakob Holderbaum'
 

options:

    app_title:          true    # append page title to main title?
    separator:          ' > '   # maintitle [separator] subtitle
