page:
    title:          'Follow the KISS'   # the html title tag
    description:    'description'       # your brief pagedescription in one sentence (eg. My Blog)
    author:         'Jakob Holderbaum'
    copyright:      'Jakob Holderbaum'
 
options:
    app_title:      true    # pages append their title to the main title
    separator:      ' > '   # maintitle[separator]subtitle
 
 
# System relevant section # {{{
#  you should only change values beyond this line if you're exactly know what
#  you're doing
 
html:
    title:          '{{TITLE}}'
    navlist:        '{{NAVIGATION}}'
    author:         '{{AUTHOR}}'
    date:           '{{DATE}}'
    dateformat:     '%d.%m.%Y - %H:%M'    # as given from strftime
 
    css_nav:        'navigation'
 
    css_nav_elem_sel:   'elem_sel'
    css_nav_elem_unsel: 'elem_unsel'
 



system:
    paths:
        html:       'web'
        pages:      'pgs'
        blocks:     'blk'
        templates:  'tpl'
    
    page_order: 'order'
 
    extensions:
        html:       '.html'
        block:      '.blk'
        page_block: '.blks'
        page_title: '.title'
 
    editor:     'vim'
 
# }}}
