page:

    title:              'Foooobar!'
    description:        'Noch in Arbeit...'
    author:             'Nils Schweinsberg'
    copyright:          'Nils Schweinsberg'
 

options:

    app_title:          true
    separator:          ' - '
